application:
  name: familie-tilbake-e2e
server:
  servlet:
    context-path: /
  port: 8032
spring:
  main:
    allow-bean-definition-overriding: true

no.nav.security.jwt:
  client:
    registration:
      familie-tilbake:
        resource-url: ${FAMILIE_TILBAKE_API_URL}
        token-endpoint-url: http://localhost:1111/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_TILBAKE_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-historikk:
        resource-url: ${FAMILIE_HISTORIKK_API_URL}
        token-endpoint-url: http://localhost:1111/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_HISTORIKK_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic

FAMILIE_TILBAKE_API_URL: http://localhost:8030
FAMILIE_TILBAKE_SCOPE: api://${TILBAKE_CLIENT_ID}/.default
FAMILIE_HISTORIKK_API_URL: http://localhost:8050
FAMILIE_HISTORIKK_SCOPE: api://${HISTORIKK_CLIENT_ID}/.default
TILBAKE_CLIENT_ID: ${TILBAKE_CLIENT_ID}

logging:
  level:
    root: INFO
