services:
  familie-mock-server:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie/familie-mock-server:latest
#    image: ghcr.io/navikt/familie-mock-server/familie-mock-server:latest
#    image: familie-mock-server:latest
    ports:
      - 1337:1337
  # For Azure
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server/mock-oauth2-server:0.1.33
    ports:
      - 1111:1111
  # For STS
  nav-auth-mock:
    image: ghcr.io/navikt/nav-auth-mock/nav-auth-mock
    ports:
      - 8200:8200
  postgres-tilbake:
    image: postgres:14
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familie-tilbake
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5432:5432
  familie-integrasjoner:
    restart: always
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie/familie-integrasjoner:latest
    depends_on:
      - familie-mock-server
      - mock-oauth2-server
      - nav-auth-mock
    volumes:
      - ./modig:/root/.modig
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      APPD_ENABLED: 0
      INTEGRASJONER_CLIENT_ID: ${INTEGRASJONER_CLIENT_ID}
      INTEGRASJONER_CLIENT_SECRET: ${INTEGRASJONER_CLIENT_SECRET}
      INFOTRYGD_KS_SCOPE: ${INTEGRASJONER_INFOTRYGD_KS_SCOPE}
      AAD_GRAPH_SCOPE: ${INTEGRASJONER_AAD_GRAPH_SCOPE}
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://mock-oauth2-server:1111/v2.0/token
    ports:
      - 8085:8085
  familie-tilbake:
    restart: always
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie/familie-tilbake:latest
#    image: familie-tilbake:latest
    depends_on:
      - postgres-tilbake
      - mock-oauth2-server
      - familie-integrasjoner
      - nav-auth-mock
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      APPD_ENABLED: 0
      FAMILIE_INTEGRASJONER_SCOPE: ${INTEGRASJONER_SCOPE}
      AZURE_APP_CLIENT_ID: ${TILBAKE_CLIENT_ID}
      TILBAKE_CLIENT_ID: ${TILBAKE_CLIENT_ID}
      TILBAKE_CLIENT_SECRET: ${TILBAKE_CLIENT_SECRET}
      BA_SAK_CLIENT_ID: ${BA_SAK_CLIENT_ID}
      FAMILIE_TILBAKE_FRONTEND_CLIENT_ID=: ${FAMILIE_TILBAKE_FRONTEND_CLIENT_ID}
    ports:
      - 8030:8030
