services:
  familie-mock-server:
    image: europe-north1-docker.pkg.dev/nais-management-233d/tilbake/familie-mock-server:latest
    platform: linux/amd64
#    image: ghcr.io/navikt/familie-mock-server/familie-mock-server:latest
#    image: familie-mock-server:latest
    ports:
      - 1337:1337
  # For Azure
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server/mock-oauth2-server:0.1.33
    ports:
      - 1111:1111
  # For STS
  nav-auth-mock:
    image: ghcr.io/navikt/nav-auth-mock/nav-auth-mock
    ports:
      - 8200:8200
  postgres-tilbake:
    image: postgres:14
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familie-tilbake
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5432:5432
  familie-integrasjoner:
    restart: always
    platform: linux/amd64
    image: europe-north1-docker.pkg.dev/nais-management-233d/tilbake/familie-integrasjoner:latest
    depends_on:
      - familie-mock-server
      - mock-oauth2-server
      - nav-auth-mock
    volumes:
      - ./modig:/root/.modig
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      APPD_ENABLED: 0
      INTEGRASJONER_CLIENT_ID: dev-fss.teamfamilie.familie-integrasjoner
      INTEGRASJONER_CLIENT_SECRET: no_need_in_test
      LOGGING_LEVEL_NO_NAV_SECURITY: DEBUG
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://mock-oauth2-server:1111/v2.0/token
    ports:
      - 8085:8085
  familie-tilbake:
    restart: always
    platform: linux/amd64
    image: europe-north1-docker.pkg.dev/nais-management-233d/tilbake/familie-tilbake:2025.01.27-10.59-c5a441f
#    image: familie-tilbake:latest
    depends_on:
      - postgres-tilbake
      - mock-oauth2-server
      - familie-integrasjoner
      - nav-auth-mock
    env_file: .local/famile-tilbake.env
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      APPD_ENABLED: 0
      FAMILIE_INTEGRASJONER_SCOPE: api://dev-fss.teamfamilie.familie-integrasjoner/.default
      AZURE_APP_CLIENT_ID: dev-gcp.tilbake.tilbakekreving-backend
      TILBAKE_CLIENT_ID: dev-gcp.tilbake.tilbakekreving-backend
      TILBAKE_CLIENT_SECRET: no_need_in_test
      INVALID_BA_SAK_CLIENT_ID: 1f4d13c7-cb63-48c4-b415-591403ab6c97
      LOGGING_LEVEL_NO_NAV_SECURITY: DEBUG

    ports:
      - 8030:8030
